import { ACTIVITY_ACTIONS, COMPLAINT_STATUS, ACTOR_TYPES } from "~/database/schema";

export const ACTIVITY_LABELS = {
  [ACTIVITY_ACTIONS.SUBMITTED]: 'Soumis',
  [ACTIVITY_ACTIONS.STATUS_CHANGED]: 'Statut modifié',
  [ACTIVITY_ACTIONS.NOTE_ADDED]: 'Note',
  [ACTIVITY_ACTIONS.QUESTION_ASKED]: 'Question posée',
  [ACTIVITY_ACTIONS.RESPONSE_ADDED]: 'Réponse',
  [ACTIVITY_ACTIONS.ASSIGNED_TO_INSPECTOR]: 'Assigné à un inspecteur',
  [ACTIVITY_ACTIONS.ASSIGNED_TO_JUDGE]: 'Assigné à un juge',
  [ACTIVITY_ACTIONS.RECOMMENDATION_ADDED]: 'Recommandation',
  [ACTIVITY_ACTIONS.DECISION_MADE]: 'Décision'
} as const;

export const ACTOR_TYPE_LABELS = {
  [ACTOR_TYPES.COMPLAINANT]: 'Plaignant',
  [ACTOR_TYPES.INSPECTOR]: 'Inspecteur',
  [ACTOR_TYPES.JUDGE]: 'Juge',
  [ACTOR_TYPES.SYSTEM]: 'Système'
} as const;

export const STATUS_LABELS = {
  [COMPLAINT_STATUS.SUBMITTED]: 'Soumis',
  [COMPLAINT_STATUS.UNDER_INVESTIGATION]: 'En cours d\'enquête',
  [COMPLAINT_STATUS.AWAITING_JUDGMENT]: 'En attente de jugement',
  [COMPLAINT_STATUS.CLOSED]: 'Fermé'
} as const;

// Workflow simplifié : Note -> Recommandation (inspector) -> Décision (judge) + changements de statut directs
export const WORKFLOW_ACTIONS = {
  INSPECTOR: [
    { type: 'activity', value: ACTIVITY_ACTIONS.NOTE_ADDED, label: ACTIVITY_LABELS[ACTIVITY_ACTIONS.NOTE_ADDED] },
    { type: 'activity', value: ACTIVITY_ACTIONS.RECOMMENDATION_ADDED, label: ACTIVITY_LABELS[ACTIVITY_ACTIONS.RECOMMENDATION_ADDED] },
    { type: 'status', value: COMPLAINT_STATUS.UNDER_INVESTIGATION, label: STATUS_LABELS[COMPLAINT_STATUS.UNDER_INVESTIGATION] },
    { type: 'status', value: COMPLAINT_STATUS.AWAITING_JUDGMENT, label: STATUS_LABELS[COMPLAINT_STATUS.AWAITING_JUDGMENT] },
    { type: 'status', value: COMPLAINT_STATUS.CLOSED, label: STATUS_LABELS[COMPLAINT_STATUS.CLOSED] }
  ],
  JUDGE: [
    { type: 'activity', value: ACTIVITY_ACTIONS.NOTE_ADDED, label: ACTIVITY_LABELS[ACTIVITY_ACTIONS.NOTE_ADDED] },
    { type: 'activity', value: ACTIVITY_ACTIONS.DECISION_MADE, label: ACTIVITY_LABELS[ACTIVITY_ACTIONS.DECISION_MADE] },
    { type: 'status', value: COMPLAINT_STATUS.UNDER_INVESTIGATION, label: STATUS_LABELS[COMPLAINT_STATUS.UNDER_INVESTIGATION] },
    { type: 'status', value: COMPLAINT_STATUS.AWAITING_JUDGMENT, label: STATUS_LABELS[COMPLAINT_STATUS.AWAITING_JUDGMENT] },
    { type: 'status', value: COMPLAINT_STATUS.CLOSED, label: STATUS_LABELS[COMPLAINT_STATUS.CLOSED] }
  ]
} as const;
