import { ACTIVITY_ACTIONS, COMPLAINT_STATUS } from "~/database/schema";

export const STATUS_TRANSITIONS = {
  // Actions d'activité qui changent automatiquement le statut
  [ACTIVITY_ACTIONS.NOTE_ADDED]: COMPLAINT_STATUS.UNDER_INVESTIGATION,
  [ACTIVITY_ACTIONS.RECOMMENDATION_ADDED]: COMPLAINT_STATUS.AWAITING_JUDGMENT,
  [ACTIVITY_ACTIONS.DECISION_MADE]: COMPLAINT_STATUS.CLOSED,
  // Changements de statut directs
  [COMPLAINT_STATUS.UNDER_INVESTIGATION]: COMPLAINT_STATUS.UNDER_INVESTIGATION,
  [COMPLAINT_STATUS.AWAITING_JUDGMENT]: COMPLAINT_STATUS.AWAITING_JUDGMENT,
  [COMPLAINT_STATUS.CLOSED]: COMPLAINT_STATUS.CLOSED,
} as const;

export const AUTO_STATUS_CHANGE_ACTIONS = [
  ACTIVITY_ACTIONS.NOTE_ADDED,
  ACTIVITY_ACTIONS.RECOMMENDATION_ADDED,
  ACTIVITY_ACTIONS.DECISION_MADE,
  // Changements de statut directs
  COMPLAINT_STATUS.UNDER_INVESTIGATION,
  COMPLAINT_STATUS.AWAITING_JUDGMENT,
  COMPLAINT_STATUS.CLOSED,
] as const;

export const shouldAutoChangeStatus = (action: string): boolean => {
  return AUTO_STATUS_CHANGE_ACTIONS.includes(action as typeof AUTO_STATUS_CHANGE_ACTIONS[number]);
};

export const getNewStatusForAction = (action: string): string | null => {
  return STATUS_TRANSITIONS[action as keyof typeof STATUS_TRANSITIONS] || null;
};
